### ISSUE TITLE
HACS

### ISSUE THREAD

**Issue by BartVanBouwel** [sdebruyn/homeassistant-bpost-integration#30]
After installing the "my bpost" repositorie with the HACS, it doesn't show a configuration window for the email and activation code. I get the message "Pending restart". After a restart of HA, the integreation does not add any sensors. The HA log doesn't show anything about the bpost integration.
Have I missed something?

**Comment by sdebruyn** [comment]
When you install it with HACS, you should restart Home Assistant. Then, when you go to your integrations, you can add the *bpost* integration like a regular integration. When you try to add it, Home Assistant will ask you about your email address and the verification code.

I think you forgot to add the integration after restarting HA?

**Comment by BartVanBouwel** [comment]
:-) That works! Thanks!!
